Repository RedHatQE/hive-claim-manager, pull requests merged in 2024-05, with the labels that each got.

#1 Update the Readme
  .pre-commit-config.yaml
  .release-it.json
  Dockerfile
  README.md
  src/App.js
  src/ClsuerClaimsComp.js
  src/ClusterPoolsComp.js
  src/DeleteAllClaimsComp.js
  src/Login.js
Labels: verified, size/L, branch-main, approved-rnetser

#2 Add healthcheck
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/App.js
  src/ClusterClaimsComp.js
  src/ClusterPoolsComp.js
  src/DeleteAllClaimsComp.js
  src/Login.js
  src/index.css
Labels: size/L, branch-main

#5 User production to run servers (flask and react)
  .dockerignore
  Dockerfile
  README.md
  api/api.py
  api/app.py
  api/manage_users.py
  api/utils.py
  entrypoint.sh
  package-lock.json
  poetry.lock
  pyproject.toml
  src/App.js
  src/ClusterClaims.js
  src/ClusterPools.js
  src/DeleteAllClaims.js
  src/IsUserAuthenticated.js
Labels: verified, size/XXL, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1022

#7 Add super user
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  api/api.py
  api/app.py
  api/config.py
  api/manage_users.py
  api/models.py
  api/utils.py
  development/config/nginx/site-confs/default.conf
  development/users.yaml
  docker-compose.example.yaml
  entrypoint.sh
  package-lock.json
  public/index.html
  src/ClusterClaims.js
  src/Login.js
Labels: verified, size/XXL, can-be-merged, branch-main, JIRA:MSINTEROP-1034, approved-myakove

#9 Update kubeconfig url
  src/ClusterClaims.js
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove, JIRA:MSINTEROP-1047

#13 Fix user login logic
  src/App.js
  src/ClusterClaims.js
  src/ClusterPools.js
  src/DeleteAllClaims.js
  src/IsUserAuthenticated.js
  src/UserAuthentication.js
Labels: verified, size/L, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1058

#15 Fix user login logic again !!!
  src/App.js
  src/UserAuthentication.js
Labels: verified, size/S, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1061

#17 User window.location.replace()
  src/App.js
  src/Login.js
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1065

#19 fetch cluster claims every 30s
  src/ClusterClaims.js
Labels: verified, size/S, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1067

#21 multi-cluster deletion in process, define ocp client once, add prettier to pre-commit
  .pre-commit-config.yaml
  .release-it.json
  api/.release-it.json
  api/api.py
  api/app.py
  api/utils.py
  poetry.lock
  public/index.html
  pyproject.toml
  renovate.json
  src/ClusterClaims.js
Labels: verified, size/L, can-be-merged, branch-main, approved-myakove, JIRA:MSINTEROP-1069

#27 fix typo in function
  src/App.js
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove, JIRA:MSINTEROP-1080

#29 Fix claim creds
  api/utils.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1082

#31 Add user name to delete all button
  src/DeleteAllClaims.js
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1084

#33 Delete button match the operation
  api/api.py
  api/utils.py
  entrypoint.sh
  package-lock.json
  package.json
  src/App.js
  src/ClusterClaims.js
  src/ClusterPools.js
  src/ConsoleLog.js
  src/DeleteAllClaims.js
  src/EventBus.js
  src/Logout.js
Labels: verified, size/XL, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1086

#35 Store deleted claims in progress in API side
  api/api.py
  api/utils.py
  src/ClusterClaims.js
  src/DeleteAllClaims.js
Labels: verified, size/M, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1098

#40 Allow persistent db
  README.md
  api/config.py
  api/manage_users.py
  docker-compose.example.yaml
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove, JIRA:MSINTEROP-1108

#42 Rename manage_users.py => init_db.py
  api/init_db.py
  entrypoint.sh
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1111

#48 refactor login page
  src/Login.js
Labels: verified, size/L, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-1123

#50 Refactor db functions and usage
  api/api.py
  api/claims_db.py
  api/claims_delete_in_progress.py
  api/init_db.py
  api/users_db.py
  api/utils.py
Labels: verified, size/L, can-be-merged, branch-main, approved-myakove, JIRA:MSINTEROP-1131
